# Generated by Django 6.0.6 on 2026-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=500, verbose_name='Содержимое')),
                ('preview_image', models.ImageField(upload_to='thumbnails/')),
                ('is_published', models.BooleanField()),
                ('views', models.IntegerField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
